apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: postgres
    app: api_gateway
spec:
      containers:
      - image: postgres:latest
        name: postgres
        ports:
        - name: postgres
          conatinerPort: 5432
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
      volumes:
          - name: postgres-storage
            hostPath:
              path: /var/lib/postgresql/data
